# Generated by Django 3.2.9 on 2021-12-03 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='note',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='note',
            name='user',
            field=models.CharField(max_length=100),
        ),
    ]
